<?php
// Cura service pages: content for the 9 ride types, built from the Services Single (212) structure.
return [
 ['doctor-appointment-rides','Doctor and specialist visits',
  'service-doctor-visits/senior-woman-smiling-in-medical-office-lobby.webp',
  'service-doctor-visits/doctor-talking-with-senior-male-patient.webp',
  'service-doctor-visits/senior-woman-filling-out-form-in-waiting-room.webp',
  'Getting to the doctor should not be the hard part. We drive you to checkups, specialist visits, lab work and imaging across the Baton Rouge area, and we help you from your front door to the check-in desk.<br><br>Tell us the appointment time and we plan the pickup around it, so you arrive calm and on time. When the visit is over, we bring you home.',
  ['Door-to-door help at both ends','Pickup planned around your appointment','Help with walkers, canes and wheelchairs','Rides to labs, imaging and specialists','A clear price before you book'],
  [['Can you wait during my appointment?','Tell us when you book. We can plan a round trip and schedule your return pickup with you.'],['Can a family member come along?','Yes. Let us know when you book so we can plan for it.'],['What if my appointment runs late?','Call or text us at (225) 363-0845 and we will work with you on the return pickup.']]],
 ['dialysis-transportation','Dialysis rides',
  'service-treatment-rides/patients-in-clinic-treatment-chairs.webp',
  'service-treatment-rides/patients-resting-in-teal-treatment-chairs.webp',
  'service-treatment-rides/woman-resting-in-treatment-chair-at-clinic.webp',
  'Dialysis runs on a schedule, and your ride should too. We set up standing rides to your dialysis center on the days and times you need, so you do not have to book every trip.<br><br>After treatment you may feel tired. We help you from the chair to the car and all the way to your door.',
  ['Standing rides on your dialysis days','Help to and from the treatment chair','Patient drivers who never rush you','Easy changes when your schedule shifts','A clear price before you book'],
  [['Can I set up rides for every dialysis day?','Yes. We can set a recurring schedule, such as three times a week, and handle each ride after that.'],['What if my chair time changes?','Call or text us and we will update your pickup times.'],['Do you help after treatment?','Yes. We help you from the center to the car and into your home.']]],
 ['wheelchair-transportation','Wheelchair transportation',
  'service-wheelchair/wheelchair-user-with-driver-at-van-lift.webp',
  'service-wheelchair/helping-man-in-wheelchair-into-van.webp',
  'service-wheelchair/assistant-helping-wheelchair-user-board-vehicle.webp',
  'If you use a wheelchair, walker or scooter, you deserve a ride that is planned around you. Our drivers give patient, hands-on help from your door to your seat and back again.<br><br>Tell us about your mobility needs when you book, and we will plan the right ride for you.',
  ['Hands-on help from door to seat','Rides for wheelchair, walker and scooter users','Patient, careful drivers','Pickup from home or a care facility','A clear price before you book'],
  [['Do I need to bring my own wheelchair?','Yes, please bring the wheelchair or mobility aid you use every day. Tell us about it when you book.'],['Can you help me transfer?','Tell us what kind of help you need when you book so we can plan for it.'],['Can a caregiver ride with me?','Yes. Let us know when you book.']]],
 ['hospital-discharge-rides','Hospital discharge rides',
  'service-discharge/caregiver-pushing-senior-woman-in-wheelchair-hospital-hallway.webp',
  'service-discharge/woman-with-man-in-wheelchair-ready-to-leave-hospital-room.webp',
  'service-discharge/nurse-assisting-senior-man-in-wheelchair-entrance.webp',
  'Going home after a hospital stay, surgery or outpatient procedure should feel calm, not rushed. We pick you up at the hospital and help you all the way inside your home.<br><br>Discharge times can change. Call us as soon as you know, and we will work with you on the pickup.',
  ['Pickup from the hospital or surgery center','Help from the room to the car and into your home','Patient drivers who take it slow','Help for walkers and wheelchairs','A clear price before you book'],
  [['What if my discharge time changes?','Call or text us at (225) 363-0845 and we will work with you on the pickup time.'],['Can a family member book for me?','Yes. Family members and caregivers can book rides for a loved one.'],['Can you stop at the pharmacy on the way home?','Ask us when you book and we will plan for it.']]],
 ['treatment-and-therapy-rides','Treatment and therapy rides',
  'service-treatment-rides/patient-in-treatment-chair-with-nurse.webp',
  'service-treatment-rides/smiling-woman-during-outpatient-treatment.webp',
  'blog-therapy/senior-woman-resistance-band-physical-therapy.webp',
  'Ongoing treatment takes energy. Let us handle the drive. We take you to chemotherapy, infusions, physical therapy, wound care and other regular appointments.<br><br>Set up one ride or a standing schedule, and we will help you to and from the door every time.',
  ['Rides to chemo, infusions and therapy','One-time or standing schedules','Door-to-door help every trip','Patient drivers after long sessions','A clear price before you book'],
  [['Can I schedule all my therapy sessions at once?','Yes. We can set up recurring rides for your treatment schedule.'],['What if I feel unwell after treatment?','Our drivers take it slow and help you all the way inside. For a medical emergency, always call 911.'],['Can someone ride with me?','Yes. Let us know when you book.']]],
 ['senior-and-everyday-rides','Senior and everyday rides',
  'service-everyday/senior-couple-walking-out-of-building-together.webp',
  'service-everyday/senior-woman-with-groceries-at-car.webp',
  'service-everyday/caregiver-helping-senior-woman-with-walker-at-home.webp',
  'Life is more than appointments. We give seniors and riders with mobility needs safe rides for errands, the pharmacy, the grocery store and visits with family.<br><br>You get the same door-to-door help and patient drivers on every ride, big or small.',
  ['Errands, shopping and pharmacy runs','Visits with family and friends','Door-to-door help with bags and walkers','Patient, friendly drivers','A clear price before you book'],
  [['Do I need a medical reason to ride?','No. We give rides for everyday errands and visits too.'],['Can you help carry my bags?','Yes. Our drivers help you to the door.'],['Can I book a round trip?','Yes. We take you there and bring you home.']]],
 ['prescription-pickup-and-delivery','Prescription pickups',
  'service-prescription/pharmacist-helping-senior-couple.webp',
  'service-prescription/pharmacist-handing-prescription-to-senior-woman.webp',
  'service-prescription/caregiver-giving-senior-man-medication.webp',
  'When getting to the pharmacy is hard, we can help. We give you a ride to pick up your prescriptions, or we pick them up and bring them to your door.<br><br>Call us with the pharmacy and the pickup details, and we will take care of the rest.',
  ['Rides to and from your pharmacy','Pickup and delivery to your door','Help for riders with walkers and wheelchairs','Friendly, patient drivers','A clear price before you book'],
  [['Can you pick up my prescription for me?','Call us with the details. Your pharmacy may need you to set up who can pick up for you.'],['Can you stop at the pharmacy after an appointment?','Yes. Ask when you book and we will plan the stop.'],['How do I book a pickup?','Call or text (225) 363-0845, or use the ride request form.']]],
 ['long-distance-medical-transportation','Long-distance medical trips',
  'service-long-distance/van-on-rural-road-at-sunrise.webp',
  'service-long-distance/white-passenger-van-on-highway.webp',
  'service-long-distance/oak-tree-lined-road-spanish-moss.webp',
  'Some care is far from home. We drive you to specialists and hospitals outside the Baton Rouge area, with the same door-to-door help as every local ride.<br><br>Tell us where you are going and when. We will plan the trip, the timing and any stops with you.',
  ['Rides to specialists outside the area','Trips planned around your appointment','Door-to-door help at both ends','Comfort stops when you need them','A clear price before you book'],
  [['How far will you drive?','Tell us where you need to go and we will let you know if we can help.'],['Can you wait and bring me home the same day?','Yes. Ask about a round trip when you book.'],['How much notice do you need?','As much as you can give us. Long trips take more planning.']]],
 ['recurring-rides','Recurring ride schedules',
  'service-facilities/nurse-scheduling-on-phone-at-reception-desk.webp',
  'service-facilities/medical-office-scheduler-on-phone-at-desk.webp',
  'service-treatment-rides/patients-resting-in-teal-treatment-chairs.webp',
  'If you have regular appointments, set your rides up once and let us handle the rest. We set standing rides for dialysis, therapy, treatment and other care on the same days each week.<br><br>We confirm before each ride, and you can call us anytime to make a change.',
  ['Same days and times each week','Confirmations before each ride','Easy changes by phone or text','Door-to-door help every trip','A clear price before you book'],
  [['How do I set up a recurring schedule?','Call or text (225) 363-0845 with your appointment days and times.'],['Can a care facility set up rides for a resident?','Yes. Facilities and case managers can call us to set up rides.'],['What if I need to skip a ride?','Call or text us and we will update your schedule.']]],
];
